# Generated by Django 4.2.11 on 2026-04-01 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('nouvelle_demande', 'Nouvelle demande'), ('demande_assignee', 'Demande assignée'), ('demande_traitee', 'Demande traitée'), ('statut_modifie', 'Statut modifié'), ('rdv_confirme', 'RDV confirmé'), ('rdv_rappel', 'Rappel RDV'), ('rdv_annule', 'RDV annulé'), ('nouveau_message', 'Nouveau message'), ('document_ajoute', 'Document ajouté'), ('rapport_disponible', 'Rapport disponible'), ('facture_disponible', 'Facture disponible'), ('facture_en_retard', 'Facture en retard')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('demande_id', models.UUIDField(blank=True, null=True)),
                ('consultation_id', models.UUIDField(blank=True, null=True)),
                ('document_id', models.UUIDField(blank=True, null=True)),
                ('invoice_id', models.UUIDField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_2c3905_idx')],
            },
        ),
    ]
