# Generated by Django 5.1.5 on 2026-04-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('nouvelle_demande', 'Nouvelle demande'), ('demande_assignee', 'Demande assignée'), ('demande_traitee', 'Demande traitée'), ('statut_modifie', 'Statut modifié'), ('rdv_confirme', 'RDV confirmé'), ('rdv_rappel', 'Rappel RDV'), ('rdv_annule', 'RDV annulé'), ('nouveau_message', 'Nouveau message'), ('document_ajoute', 'Document ajouté'), ('rapport_disponible', 'Rapport disponible'), ('facture_disponible', 'Facture disponible'), ('facture_en_retard', 'Facture en retard'), ('nouveau_client', 'Nouveau client')], max_length=30),
        ),
    ]
