# Generated by Django 5.1.5 on 2026-04-05 11:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#00B2FF', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'publication_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(default='fr', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirm_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'newsletter_subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'db_table': 'publication_tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=400)),
                ('excerpt', models.TextField(blank=True, max_length=600)),
                ('content', models.TextField()),
                ('reading_time', models.PositiveIntegerField(default=0)),
                ('pub_type', models.CharField(choices=[('article', 'Article'), ('etude', 'Étude juridique'), ('bulletin', 'Bulletin réglementaire'), ('analyse', 'Analyse'), ('guide', 'Guide pratique'), ('jurisprudence', 'Jurisprudence commentée'), ('rapport', 'Rapport')], default='article', max_length=30)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('ar', 'العربية'), ('en', 'English')], default='fr', max_length=5)),
                ('author_name', models.CharField(blank=True, max_length=200)),
                ('author_bio', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='publications/covers/')),
                ('cover_alt', models.CharField(blank=True, max_length=200)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='publications/pdf/')),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('revision', 'En révision'), ('planifie', 'Planifié'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20)),
                ('access', models.CharField(choices=[('public', 'Public — accessible à tous'), ('members', 'Membres — connectés uniquement'), ('premium', 'Premium — abonnés uniquement')], default='public', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_newsletter', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('canonical_url', models.URLField(blank=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='publications.category')),
                ('related_publications', models.ManyToManyField(blank=True, to='publications.publication')),
                ('tags', models.ManyToManyField(blank=True, related_name='publications', to='publications.tag')),
            ],
            options={
                'db_table': 'publications',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254)),
                ('content', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('en_attente', 'En attente de modération'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('spam', 'Spam')], default='en_attente', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='publications.comment')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='publications.publication')),
            ],
            options={
                'db_table': 'publication_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['status', 'published_at'], name='publication_status_f6e566_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['pub_type', 'status'], name='publication_pub_typ_a09575_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['category', 'status'], name='publication_categor_14722f_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['is_featured', 'status'], name='publication_is_feat_beab10_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['slug'], name='publication_slug_d14154_idx'),
        ),
    ]
