# Generated by Django 4.2.11 on 2026-04-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('physique', 'Personne physique'), ('morale', 'Personne morale')], default='physique', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='raison_sociale',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='speciality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('expert', 'Expert'), ('admin', 'Administrateur')], default='client', max_length=20),
        ),
    ]
