# Generated by Django 4.2.11 on 2026-04-01 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('domain', models.CharField(choices=[('droit_affaires', 'Droit des affaires'), ('rgpd', 'RGPD / Cybersécurité'), ('droit_ia', "Droit de l'IA"), ('propriete_intellectuelle', 'Propriété intellectuelle'), ('droit_numerique', 'Droit du numérique'), ('immobilier', 'Immobilier'), ('gouvernance', 'Gouvernance')], max_length=50)),
                ('description', models.TextField()),
                ('urgency', models.CharField(choices=[('normale', 'Normale'), ('urgente', 'Urgente'), ('critique', 'Critique')], default='normale', max_length=20)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('assignee', 'Assignée'), ('en_cours', 'En cours'), ('en_revision', 'En révision'), ('traitee', 'Traitée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('treated_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['fournisseur', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_demandes', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'demandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='demandes.demande')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'demande_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('created', 'Créée'), ('assigned', 'Assignée'), ('status_changed', 'Statut modifié'), ('note_added', 'Note ajoutée'), ('doc_added', 'Document ajouté'), ('concluded', 'Clôturée')], max_length=30)),
                ('old_value', models.CharField(blank=True, max_length=100)),
                ('new_value', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='demandes.demande')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'demande_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='demande',
            index=models.Index(fields=['client', 'status'], name='demandes_client__4a4940_idx'),
        ),
        migrations.AddIndex(
            model_name='demande',
            index=models.Index(fields=['assigned_to', 'status'], name='demandes_assigne_7ebd61_idx'),
        ),
        migrations.AddIndex(
            model_name='demande',
            index=models.Index(fields=['domain'], name='demandes_domain_bec5db_idx'),
        ),
        migrations.AddIndex(
            model_name='demande',
            index=models.Index(fields=['urgency', 'status'], name='demandes_urgency_e7ffbc_idx'),
        ),
    ]
